database:
  host: localhost
  user: postgres
  password: root
  dbname: notes-go
  port: 5432
  sslmode: disable
  timezone: Asia/Shanghai
application:
  port: 8080
  env: development
  log_level: debug
  log_file: logs/app.log
  log_max_size: 50
  log_max_backups: 3
  log_max_age: 28